// This file is generated by Slice Machine. Update with care!

import ImageSlice from './ImageSlice';
import TestCard from './TestCard';

export {
	ImageSlice,
	TestCard,
};

export const components = {
	image_slice: ImageSlice,
	test_card: TestCard,
};
